root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
pre_cmd = [
    # "go generate soikke.li/moreplease/sites/sql/...",
    "templ generate",
    "go run soikke.li/moreplease/sites/sql/bin/render",
    "www/node_modules/.bin/esbuild ./www/db/stmt.ts ./www/components/example.ts --external:fs --external:path --bundle --outdir=assets",
]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 1000
exclude_dir = ["tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["sh", "go", "templ", "html", "css", "sql", "xml", "ts"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
rerun = true
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = true

[proxy]
app_port = 9000
enabled = true
proxy_port = 9001

[screen]
clear_on_rebuild = false
keep_scroll = true
