root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
pre_cmd = ["scripts/prebuild.sh -s sites/sql"]
args_bin = []
bin = "tmp/moreplease -metrics tmp/metrics.db"
cmd = "go build -o tmp/moreplease"
delay = 1000
exclude_dir = [
    "**/tmp",
    "**/vendor",
    "**/testdata",
    "data",
    "**/data",
    "cmd/metrics",
]
exclude_file = []
exclude_regex = [
    "_test.go",
    "_templ.go",
    ".html",
    "generated_imports.go",
    ".index",
]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["sh", "go", "templ", "html", "css", "sql", "xml", "ts"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
rerun = true
rerun_delay = 1000
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = true

[proxy]
app_port = 8080
enabled = true
proxy_port = 8081

[screen]
clear_on_rebuild = true
keep_scroll = true
