root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
pre_cmd = ["scripts/prebuild.sh -s sites/sql"]
cmd = "go build -o tmp/moreplease"
bin = "tmp/moreplease"
args_bin = ["-metrics tmp/metrics.db"]
include_ext = ["sh", "go", "templ", "html", "css", "sql", "xml", "ts"]
exclude_regex = [
    "_test\\.go",
    "_templ\\.go",
    "\\.html",
    "generated_imports\\.go",
    "\\.index",
    ".*/tmp/.*",
    ".*/vendor/.*",
    ".*/testdata/.*",
    ".*/node_modules/.*",
    ".*/data/.*",
    ".*/cmd/metrics/.*",
    ".*/assets/.*",
]
log = "build-errors.log"
rerun = true
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = true

[proxy]
app_port = 8080
enabled = true
proxy_port = 8081

[screen]
keep_scroll = true
