# fly.toml app configuration file generated for moreplease on 2025-01-18T19:40:04-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moreplease'
primary_region = 'sea'

[build]
  [build.args]
    GO_VERSION = '1.23.2'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
